variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - pipelines

helm:
  stage: pipelines
  trigger:
    include:
      - "/sausage-store-chart/.gitlab-ci.yml"
  only:
    changes:
      - sausage-store-chart/**/*

#kubernetes:
#  stage: pipelines
#  trigger:
#    include:
#      - "/k8s.gitlab-ci.yml"
#  only:
#    changes:
#      - kubernetes/**/*
