variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - relese
  - deploy

relese:
  stage: relese
  image:
    name: tzar/helm-kubectl
    entrypoint: ['']
  script:
    - helm package sausage-store-chart
    - curl -u ${NEXUS_REPO_USER}:${NEXUS_REPO_PASS} ${NEXUS_REPO_URL} --upload-file sausagestore-*.tgz
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - changes:
        - sausage-store-chart/**/*

deploy:
  stage: deploy
  script:
    — |
    <...> Kubeconfig create automation <...>

    helm repo add nexus ${NEXUS_REPO_URL}
    helm repo update

    helm upgrade --install sausagestore \
    --set environment=test \
    --set fqdn="antipov-stas-15.k8s.praktikum-services.tech" \
    --atomic --timeout 15m \
    nexus/sausage-store-chart