variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - relese
  - deploy

relese:
  stage: relese
  image: dtzar/helm-kubectl
  script:
    - helm package sausage-store-chart
    - curl -u ${NEXUS_REPO_USER}:${NEXUS_REPO_PASS} ${NEXUS_REPO_URL} --upload-file sausagestore-*.tgz
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - changes:
        - sausage-store-chart/**/*

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  when: manual

  before_script:
    - mkdir -p .kube
    - echo "${KUBE_CONFIG}" | base64 -d > .kube/config
  script:
    - helm repo add nexus ${NEXUS_REPO_HELM_URL}
    - helm repo update
    - >
      helm upgrade --install sausagestore \
      --set environment=test \
      --set fqdn="antipov-stas-15.k8s.praktikum-services.tech" \
      --atomic --timeout 15m \
      --kubeconfig .kube/config \
        nexus/sausagestore


