---
apiVersion: v2
type: application
name: sausagestore
description: Sausage Store Helm Chart

version: 1.3.0
appVersion: "latest"

dependencies:
  - name: backend
    version: 1.3.0
  - name: frontend
    version: 1.3.0
