backend:
  image: gitlab.praktikum-services.ru:5050/std-013-59/sausage-store/sausage-backend
  tag: "latest"
  revisionHistoryLimit: 15
  imagePullPolicy: Always
  replicas: 3
  rollingUpdate:
      maxUnavailable: 2
      maxSurge: 20%
  containerPort: 8080
  environment: production
  resources:
    requests:
      memory: "300Mi"
      cpu: "200m"
    limits:
      memory: "400Mi"
      cpu: "300m"

backend-report:
  image: gitlab.praktikum-services.ru:5050/std-013-59/sausage-store/sausage-backend-report
  tag: "latest"
  revisionHistoryLimit: 15
  imagePullPolicy: Always
  environment: production
  containerPort: 8080
  minReplicas: 1
  maxReplicas: 5
  averageUtilization: 75

frontend:
  image: gitlab.praktikum-services.ru:5050/std-013-59/sausage-store/sausage-frontend
  tag: "latest"
  imagePullPolicy: Always
  revisionHistoryLimit: 15
  fqdn: antipov-stas-15.k8s.praktikum-services.tech
  replicas: 3
  environment: production
  containerPort: 8080

global:
  backServiceName: backend
  backServicePort: 8080
