image: gitlab.praktikum-services.ru:5050/std-013-59/sausage-store/sausage-backend
tag: "latest"
revisionHistoryLimit: 15
imagePullPolicy: Always
replicas: 3
rollingUpdate:
    maxUnavailable: 2
    maxSurge: 20%
containerPort: 8080
environment: production
resources:
  requests:
    memory: "300Mi"
    cpu: "200m"
  limits:
    memory: "400Mi"
    cpu: "300m"
