image: gitlab.praktikum-services.ru:5050/std-013-59/sausage-store/sausage-frontend
tag: "latest"
imagePullPolicy: Always
revisionHistoryLimit: 15
fqdn: antipov-stas-15.k8s.praktikum-services.tech
replicas: 1
environment: production
containerPort: 8080

global:
  backServiceName: backend
  backServicePort: 8080