image: gitlab.praktikum-services.ru:5050/std-013-59/sausage-store/sausage-backend-report
tag: "latest"
revisionHistoryLimit: 15
imagePullPolicy: Always
environment: production
containerPort: 8080
minReplicas: 1
maxReplicas: 5
averageUtilization: 75
