---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: aHZzLkNBRVNJRVRpd0dEamdiRy1ITlJ4aHEtRGVYZllaTGFMX2xnclY0MTItM0J6WXhjV0doNEtIR2gyY3k1ME5WTjNWM0UxU1VneU9UWmFkRlZ5WmxvNGVucFVPVGc=
type: Opaque

---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogImMzUmhjenB5ZVhWbFYyMU1lSGhZTnpsQ1FsRnhlWGxaT1E9PSIKCQl9LAoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImJtOTBZV0p2ZEdKaGJtUTZNak13TnpBelUzUmhjdz09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson