---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
  labels:
    app: backend-report
spec:
  replicas: 3
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      containers:
        - name: backend
          image: gitlab.praktikum-services.ru:5050/std-013-59/sausage-store/sausage-backend-report:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_CLOUD_VAULT_HOST
              value: std-013-09-res.praktikum-services.tech
            - name: SPRING_CLOUD_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: vault_token
          ports:
            - name: backend
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 6
      imagePullSecrets:
        - name: docker-config-secret
